name: Deploy to Dev

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://dev.devcalc.app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      - name: Build e Testes
        run: |
          cd devcalc
          mvn clean package
      - name: Deploy Simulado (Dev)
        run: echo "Deploy Dev concluído."