name: Deploy to Dev

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  deploy-dev:
    name: Deploy para Ambiente Dev
    runs-on: ubuntu-latest

    environment:
      name: dev

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build & Testes
        run: mvn clean package

      - name: Deploy Simulado (Dev)
        run: echo "Deploy para Dev concluído com sucesso."
