name: Monitoramento de Falhas

permissions:
  issues: write

on:
  workflow_dispatch:

jobs:
  create-issue-if-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Simular falha de deploy
        run: exit 1

      - name: Criar issue se falha ocorreu
        if: ${{ failure() }}
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/issues \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "title": "🚨 Deploy falhou",
              "body": "O deploy falhou automaticamente. Verifique os logs.",
              "labels": ["bug","auto-created"]
            }'