name: Runner Auto-Hospedado Simples

on:
  workflow_dispatch:

jobs:
  teste:
    runs-on: self-hosted
    steps:
      - name: Informações do sistema
        run: ver
        shell: cmd

      - name: Versão do Java
        run: java -version
        shell: cmd

      - name: Instalar e testar software adicional
        run: |
          # Baixar e instalar o curl
          bitsadmin /transfer downloadCurl /download /priority normal https://curl.se/windows/dl-8.8.0_4/curl-8.8.0_4-win64-mingw.zip curl.zip
          tar -xf curl.zip -C C:\
          set PATH=C:\curl-8.8.0_4-win64-mingw\bin;%PATH%
          
          # Testar a instalação
          curl --version
        shell: cmd