name: Teste Runner Self-Hosted

on:
  workflow_dispatch:

jobs:
  teste:
    runs-on: self-hosted
    steps:

      - name: Informações do sistema
        run: ver
        shell: cmd

      - name: Testar Java
        run: |
          set JAVA_HOME=C:\Users\55219\jdk-17.0.9_windows-x64_bin\jdk-17.0.9
          set PATH=%JAVA_HOME%\bin;%PATH%
          java -version
        shell: cmd

      - name: Instalar Nano via 7‑Zip (com Scoop)
        shell: powershell
        run: |
          $env:PATH = "$HOME\scoop\shims;$env:PATH"
          
          scoop install 7zip
          $tag = 'v7.2-22.1'
          $url = "https://github.com/okibcn/nano-for-windows/releases/download/$tag/nano-for-windows_win64_$tag.zip"
          Invoke-WebRequest -UseBasicParsing -Uri $url -OutFile nano.zip
          
          & "$HOME\scoop\apps\7zip\current\7z.exe" x nano.zip -o"$PWD\nano" -y
          
          mkdir C:\tools\nano -Force
          copy .\nano\nano.exe C:\tools\nano\nano.exe -Force
          $env:PATH = "C:\tools\nano;$env:PATH"
          
          nano --version
