name: Teste Runner Self-Hosted

on:
  workflow_dispatch:

jobs:
  teste:
    runs-on: self-hosted
    steps:
      - name: Informações do sistema
        run: ver
        shell: cmd

      - name: Testar Java
        run: |
          set JAVA_HOME=C:\Users\55219\jdk-17.0.9_windows-x64_bin\jdk-17.0.9
          set PATH=%JAVA_HOME%\bin;%PATH%
          java -version
        shell: cmd

      - name: Instalar e testar Nano
        run: |
          powershell -Command "Invoke-WebRequest -Uri 'https://www.nano-editor.org/dist/win32-support/nano-7.2.zip' -OutFile 'nano.zip'"
          powershell -Command "Expand-Archive -Path nano.zip -DestinationPath C:\nano -Force"
          C:\nano\nano.exe --version
        shell: cmd