name: Teste do Runner Self-Hosted

on:
  workflow_dispatch:

jobs:
  teste:
    runs-on: self-hosted
    steps:
      - name: Informações do sistema
        run: systeminfo
        shell: cmd

      - name: Configurar e testar Java
        run: |
          set JAVA_HOME=C:\Users\55219\jdk-17.0.9_windows-x64_bin\jdk-17.0.9
          set PATH=%JAVA_HOME%\bin;%PATH%
          java -version
          javac -version
        shell: cmd

      - name: Instalar e testar software adicional
        run:
          curl -o nano.zip https://www.nano-editor.org/dist/win32-support/nano-7.2.zip
          tar -xf nano.zip -C C:\
          
          C:\nano\nano.exe --version
        shell: cmd