name: Teste Runner Self-Hosted

on:
  workflow_dispatch:

jobs:
  teste:
    runs-on: self-hosted
    steps:

      - name: Informações do sistema
        run: ver
        shell: cmd

      - name: Testar Java
        run: |
          set JAVA_HOME=C:\Users\55219\jdk-17.0.9_windows-x64_bin\jdk-17.0.9
          set PATH=%JAVA_HOME%\bin;%PATH%
          java -version
        shell: cmd

      - name: Instalar Scoop (sem admin)
        shell: powershell
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          iwr -UseBasicParsing get.scoop.sh | iex

      - name: Adicionar Scoop ao PATH
        shell: powershell
        run: |
          $env:PATH += ";$env:USERPROFILE\scoop\shims"

      - name: Instalar Nano via Scoop
        shell: powershell
        run: |
          scoop install nano
          nano --version
