name: Variaveis e Secrets

on:
  workflow_dispatch:

jobs:
  show-vars-secrets:
    name: Exemplo de Variáveis e Segredos
    runs-on: ubuntu-latest
    env:
      STAGE: development

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Exibir variáveis não sensíveis
        run: |
          echo "APP_MODE = ${{ vars.APP_MODE }}"
          echo "SUPPORT_EMAIL = ${{ vars.SUPPORT_EMAIL }}"
          echo "STAGE (env) = $STAGE"

      - name: Passo Sensível usando secret
        run: |
          if [ -z "${{ secrets.PROD_TOKEN }}" ]; then
            echo "PROD_TOKEN não está definido."
            exit 1
          fi
          echo "Secret PROD_TOKEN está definido (não exibiremos seu valor)."