name: Exemplo de Variáveis e Segredos

on:
  workflow_dispatch:

jobs:
  configuracao:
    runs-on: self-hosted

    steps:
      - name: Mostrar variáveis de ambiente
        run: |
          echo "Modo da aplicação: ${{ vars.APP_MODE }}"
          echo "E-mail de suporte: ${{ vars.SUPPORT_EMAIL }}"
        shell: bash

  tarefa_sensivel:
    runs-on: self-hosted
    needs: configuracao

    steps:
      - name: Simular acesso protegido com PROD_TOKEN
        run: |
          echo "Autenticando com token (exemplo):"
          echo "PROD_TOKEN começa com: ${PROD_TOKEN:0:4}****"
        env:
          PROD_TOKEN: ${{ secrets.PROD_TOKEN }}
        shell: bash
